version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - npm install -g @angular/cli
      - npm install -g yarn
      - yarn install
      # insert the new value into the system config
      - sysctl fs.inotify.max_user_watches=524288
      - sysctl -p

      - yarn run lint
      - yarn run test:headless
      - yarn run e2e:ci
  build:
    commands:
      - node --max_old_space_size=4096 node_modules/@angular/cli/bin/ng build
